spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:  
    url: "jdbc:postgresql://localhost:5432/testForReactProject"  
    username: postgres  
    password: "password"
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active:
    - dev
    servlet:
      multipart:
        max-file-size: 10MB

upload-path : picture-storage
        
---
spring:
  profiles: dev
upload-path: storage-dev