import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { register } from 'timeago.js';
i18n.use(initReactI18next).init({
    resources: {
        en: {
            translations: {
                'Sign Up': 'Sign Up',
                'Password mismatch': 'Password mismatch',
                'Username': 'Username',
                'Display Name': 'Display Name',
                'Password': 'Password',
                'Password Repeat': 'Password Repeat',
                'Login': 'Login',
                'Logout': 'Logout',
                'Users': 'Users',
                "Next": "next > ",
                "Previous": "< previous",
                "Load Failure": "Load Failure",
                "User not found.": "User not found.",
                "Edit": "Edit",
                "Change Display Name": "Change Display Name",
                "Save": "Save",
                "Cancel": "Cancel",
                "Events": "Events",
                "My Profile": "My Profile",
                "There are no activities": "There are no activities",
                "Activities": "Activities",
                "Create Activity": "Create Activity",
                "Tehapy Description": "Tehapy provides the easiest way for you to attend events within or out of the university.",
                "Tehapy Activity Description": "You can list the events according to your interests, go to an event page to have detailed information, and apply to the events with application forms.",
                "Tehapy User Description": "Also, you can apply to a community that interests you and have an active role in that community's events.",
                "Sign In with Facebook": "Sign In with Facebook",
                "Sign In with Google": "Sign In with Google",
                "Load new activities": "Load new activities",
                "There are new activities": "There are new activities",
                "Delete Activity": "Delete Activity",
                "Are you sure to delete activity?": "Are you sure to delete activity?",
                "Delete My Account": "Delete My Account",
                "Are you sure to delete your account?": "Are you sure to delete your account?",
                "Follow": "Follow",
                "Name and Surname": "Name and Surname",
                "Email": "Email",
                "University": "University",
                "Branch": "Branch",
                "Events to Attend": "Events to Attend",
                "Enter the Title": "Enter the Title",
                "Enter the Description": "Enter the Description",
                "When is the event?": "When is the event?",
                "Hour": "Hour",
                "Minute": "Minute",
                "Activity Location": "Activity Location",
                "Promotional Picture": "Promotional Picture",
                "Location": "Location",
                "When": "When",
                "Name": "Name",
                "Surname": "Surname",
                "Followers": "Followers",
                "Following": "Following",
                "Join Activity": "Join Activity",
                "Are you sure to join this activity?": "Are you sure to join this activity?"
            }
        },
        tr: {
            translations: {
                'Sign Up': 'Kayıt Ol',
                'Password mismatch': 'Şifreniz eşleşmiyor',
                'Username': 'Kullanıcı Adı',
                'Display Name': 'Gözükecek İsim',
                'Password': 'Şifre',
                'Password Repeat': 'Şifre Tekrar',
                'Login': 'Giriş Yap',
                'Logout': 'Çıkış Yap',
                'Users': 'Kullanıcılar',
                "Next": "sonraki > ",
                "Previous": "< önceki",
                "Load Failure": "Liste yüklenemedi",
                "User not found.": "Kullanıcı bulunamadı.",
                "Edit": "Düzenle",
                "Change Display Name": "Görünen Adınızı Değiştiriniz",
                "Save": "Kaydet",
                "Cancel": "İptal et",
                "Events": "Etkinlikler",
                "My Profile": "Hesabım",
                "There are no activities": "Etkinlik bulunamadı",
                "Activities": "Etkinlikler",
                "Create Activity": "Etkinlik Oluştur",
                "Tehapy Description": "Tehapy üniversite ve üniversite dışındaki toplulukların, etkinliklerine katılabilmenizi en kolay yoldan sağlar.",
                "Tehapy Activity Description": "İlginizi çeken kategorilere göre etkinlikleri listeleyip, etkinliğin sayfasına girip detaylı bilgi alabilir ve başvuru formu üzerinde etkinliğe başvuru yapabilirsiniz.",
                "Tehapy User Description": "Ayrıca ilginizi çeken bir topluluğa başvurunuzu da yapabilir ve topluluğun etkinlikerinde aktif rol alabilirsiniz.",
                "Sign In with Facebook": "Facebook ile giriş yap",
                "Sign In with Google": "Google ile giriş yap",
                "Load new activities": "Yeni etkinlikleri göster",
                "There are new activities": "Yeni etkinlikler var",
                "Delete Activity": "Etkinliği sil",
                "Are you sure to delete activity?": "Etkinliği silmek istediğinizde emin misiniz?",
                "Delete My Account": "Hesabımı sil",
                "Are you sure to delete your account?": "Hesabını silmek istediğine emin misin?",
                "Follow": "Takip Et",
                "Name and Surname": "Adı ve Soyadı",
                "Email": "Email",
                "University": "Üniversite",
                "Branch": "Bölüm",
                "Events to Attend": "Katılacağı Etkinlikler",
                "Enter the Title": "Başlık",
                "Enter the Description": "Açıklama",
                "When is the event?": "Etkinlik ne zaman?",
                "Hour": "Saat",
                "Minute": "Dakika",
                "Activity Location": "Etkinlik yeri",
                "Promotional Picture": "Tanıtım Resmi",
                "Location": "Yer",
                "When": "Ne zaman",
                "Name": "İsim",
                "Surname": "Kullanıcı Soyadı",
                "Followers": "Takipçi",
                "Following": "Takip",
                "Join Activity": "Etkinliğe Katıl",
                "Are you sure to join this activity?": "Etkinliğe katılmak istediğine emin misin?"

            }
        }
    },
    fallbackLng: 'tr',
    ns: ['translations'],
    defaultNS: 'translations',
    keySeparator: false,
    interpolation: {
        escapeValue: false,
        formatSeparator: ','
    },
    react: {
        wait: true
    }
});

const timeagoTR = (number, index) => {
    return [
        ['az önce', 'şimdi'],
        ['%s saniye önce', '%s saniye içinde'],
        ['1 dakika önce', '1 dakika içinde'],
        ['%s dakika önce', '%s dakika içinde'],
        ['1 saat önce', '1 saat içinde'],
        ['%s saat önce', '%s saat içinde'],
        ['1 gün önce', '1 gün içinde'],
        ['%s gün önce', '%s gün içinde'],
        ['1 hafta önce', '1 hafta içinde'],
        ['%s hafta önce', '%s hafta içinde'],
        ['1 ay önce', '1 ay içinde'],
        ['%s ay önce', '%s ay içinde'],
        ['1 yıl önce', '1 yıl içinde'],
        ['%s yıl önce', '%s yıl içinde'],
    ][index];
}
register('tr', timeagoTR);
export default i18n;